apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "qbittorrent.fullname" . }}
  labels:
    app: {{ template "qbittorrent.fullname" . }}
    chart: {{ template "qbittorrent.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ template "qbittorrent.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "qbittorrent.fullname" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "qbittorrent.fullname" . }}
        chart: {{ template "qbittorrent.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
#      {{- if .Values.vpn.enabled }}
#      initContainers:
#        - name: create-openvpn-dir
#          image: busybox
#          command: [ 'sh', '-c', 'cp -R /openvpn/* /config/openvpn/.' ]
#          volumeMounts:
#            - name: vpn-cm
#              mountPath: /openvpn
#            - name: vpn-config
#              mountPath: /config/openvpn
#      {{- end }}
      containers:
      - name: {{ template "qbittorrent.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          privileged: true
        env:
        - name: VPN_ENABLED
        {{- if .Values.vpn.enabled }}
          value: "yes"
        {{- else }}
          value: "no"
        {{- end }}
        - name: LAN_NETWORK
          value: {{ default "10.0.0.0/8" .Values.vpn.lanNetwork | quote }}
        {{- range $key, $value := .Values.extraEnvVars }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.uiPort }}
          name: http
          protocol: TCP
        - containerPort: 8999
          name: transport-tcp
          protocol: TCP
        - containerPort: 8999
          name: transport-udp
          protocol: UDP
        volumeMounts:
        - name: qb-data
          mountPath: /config/qBittorrent
        - name: qb-downloads
          mountPath: /downloads
        - name: qb-incomplete
          mountPath: /incomplete
        - name: vpn-cm
          mountPath: /config/openvpn
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      volumes:
      - name: qb-data
      {{- if .Values.persistence.data.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qbittorrent.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: qb-downloads
      {{- if .Values.persistence.downloads.enabled }}
      {{- if .Values.persistence.downloads.useNFS }}
        nfs:
          path: {{ .Values.persistence.downloads.NFS.path }}
          server: {{ .Values.persistence.downloads.NFS.server }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "qbittorrent.fullname" . }}-downloads
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: qb-incomplete
      {{- if .Values.persistence.incomplete.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qbittorrent.fullname" . }}-incomplete
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: vpn-cm
        configMap:
          name: {{ template "qbittorrent.fullname" . }}-vpn-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
